# Generated by Django 6.0.1 on 2026-03-07 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('map_click', 'Click bản đồ'), ('save_location', 'Lưu địa điểm'), ('save_route', 'Lưu tuyến đường'), ('analyze_area', 'Phân tích vùng'), ('login', 'Đăng nhập'), ('register', 'Đăng ký')], db_index=True, max_length=50)),
                ('detail', models.JSONField(blank=True, help_text='Chi tiết bổ sung dạng JSON (không chứa dữ liệu thời tiết)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký tương tác',
                'verbose_name_plural': 'Nhật ký tương tác',
                'db_table': 'interaction_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#3b82f6', help_text='Màu nhóm (hex, vd: #3b82f6)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhóm địa điểm',
                'verbose_name_plural': 'Nhóm địa điểm',
                'db_table': 'location_group',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Tên hiển thị tuỳ chọn (vd: "Văn phòng HN")', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Ghi chú chi tiết về địa điểm')),
                ('latitude', models.FloatField(help_text='Vĩ độ, phạm vi [-90, 90]', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Kinh độ, phạm vi [-180, 180]', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.CharField(blank=True, default='', help_text='Địa chỉ tham chiếu (reverse-geocoded, không bắt buộc)', max_length=500)),
                ('is_favourite', models.BooleanField(default=False, help_text='Đánh dấu địa điểm yêu thích')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'db_table': 'user_location',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên tuyến đường hiển thị trên UI', max_length=255)),
                ('distance_km', models.FloatField(blank=True, help_text='Khoảng cách đường bộ (km), điền sau khi gọi OSRM', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.FloatField(blank=True, help_text='Thời gian di chuyển ước tính (phút)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('end_location', models.ForeignKey(db_column='end_location_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes_end', to='weather.userlocation')),
                ('start_location', models.ForeignKey(db_column='start_location_id', on_delete=django.db.models.deletion.CASCADE, related_name='routes_start', to='weather.userlocation')),
            ],
            options={
                'verbose_name': 'Tuyến đường',
                'verbose_name_plural': 'Tuyến đường',
                'db_table': 'route',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weather.locationgroup')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='weather.userlocation')),
            ],
            options={
                'verbose_name': 'Thành viên nhóm',
                'verbose_name_plural': 'Thành viên nhóm',
                'db_table': 'location_group_item',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Tên vùng phân tích', max_length=255)),
                ('radius_km', models.FloatField(help_text='Bán kính (km), phạm vi [0.1, 500]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(db_column='center_location_id', help_text='Tâm của vùng phân tích', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='weather.userlocation')),
            ],
            options={
                'verbose_name': 'Vùng phân tích',
                'verbose_name_plural': 'Vùng phân tích',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Quản trị viên')], default='user', help_text='Vai trò trong hệ thống (user / admin)', max_length=20)),
                ('bio', models.TextField(blank=True, default='', help_text='Giới thiệu ngắn về người dùng')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='URL ảnh đại diện (tuỳ chọn)', max_length=500)),
                ('default_latitude', models.FloatField(blank=True, help_text='Vĩ độ trung tâm mặc định khi mở bản đồ', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('default_longitude', models.FloatField(blank=True, help_text='Kinh độ trung tâm mặc định khi mở bản đồ', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('default_zoom', models.SmallIntegerField(default=6, help_text='Mức zoom mặc định (1–18)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('show_temperature', models.BooleanField(default=True)),
                ('show_rain', models.BooleanField(default=True)),
                ('show_wind', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_user_location_lat_lng'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'is_favourite'], name='idx_user_location_user_fav'),
        ),
        migrations.AlterUniqueTogether(
            name='locationgroupitem',
            unique_together={('group', 'location')},
        ),
    ]
