# Generated by Django 6.0.1 on 2026-04-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_add_email_tokens_and_about_content'),
        ('weather', '0005_remove_area_center_remove_area_user_and_more'),
    ]

    operations = [
    ]
